language: python
  - "3.5"
before_install:
  - pip install --user pytest pytest-cov
  - pip install --user pickle pandas numpy astropy os tqdm sklearn scipy sqlalchemy
script:
  - cd final_project
  - py.test . --doctest-modules --cov-report term --cov=. -v