language: python
python:
  - "3.6"
before_install:
  - pip install python-coveralls
  - pip install pytest pytest-cov
  - pip install pandas numpy astropy tqdm sklearn scipy sqlalchemy
script:
  - cd final_project
  - py.test . --doctest-modules --cov-report term-missing
after_success:
  - coveralls
notifications:
  email: false